apiVersion: v1
kind: Service
metadata: 
  name: test-example
  labels:
    app: test-example
spec:
  type: NodePort
  ports:
  - name: test-example
    targetPort: 8080
    protocol: TCP
    port: 8080
  selector:
    app: test-example
---    
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-example
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: test-example
    spec:
      containers:
      - name: test-example
        image: 192.168.51.28:5000/tomcat_bar:latest
        ports:
        - containerPort: 8080